version: "3.8"

services:
  kyc_mongo:
    image: mongo:4.4
    container_name: kyc_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - kyc_mongo_data:/data/db
    networks:
      - kyc_net

  kyc_redis:
    image: redis:alpine
    container_name: kyc_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass yourredispassword
    volumes:
      - kyc_redis_data:/data
    networks:
      - kyc_net

  kyc_server:
    build:
      context: ./server
    container_name: kyc_server
    restart: always
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGO_URI: "mongodb://root:example@kyc_mongo:27017/kyc_db?authSource=admin"
      JWT_SECRET: your_jwt_secret_here
      REDIS_HOST: "kyc_redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "yourredispassword"
    depends_on:
      - kyc_mongo
      - kyc_redis
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - kyc_net

  kyc_client:
    build:
      context: ./client
      args:
        REACT_APP_API_URL: http://kyc_server:5000
    container_name: kyc_client
    restart: always
    ports:
      - "80:80"
    environment:
      NODE_ENV: production
    depends_on:
      - kyc_server
    networks:
      - kyc_net

volumes:
  kyc_mongo_data:
  kyc_redis_data:

networks:
  kyc_net:
    driver: bridge
