version: "3.8"

services:
  kyc_server:
    build:
      context: ./server
    container_name: kyc_server
    restart: always
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://root:example@kyc_mongo:27017/kyc_db?authSource=admin
      JWT_SECRET: your_jwt_secret_here
      REDIS_HOST: kyc_redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: yourredispassword
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - kyc_net

  kyc_client:
    build:
      context: ./client
      args:
        REACT_APP_API_URL: http://kyc_server:5000
    container_name: kyc_client
    restart: always
    ports:
      - "80:80"
    environment:
      NODE_ENV: production
    depends_on:
      - kyc_server
    networks:
      - kyc_net

volumes:
  kyc_mongo_data:
    driver: local
  kyc_redis_data:
    driver: local

networks:
  kyc_net:
    driver: bridge
